import { timingSafeEqual } from 'node:crypto';

const XENDIT_BASE = 'https://api.xendit.co';

function apiKey(): string {
  const key = process.env.XENDIT_API_KEY;
  if (!key) throw new Error('XENDIT_API_KEY is not configured');
  return key;
}

/** Xendit's REST API uses HTTP Basic Auth with the API key as the username
 *  and an empty password — not a bearer token. */
function authHeader(): string {
  return 'Basic ' + Buffer.from(`${apiKey()}:`).toString('base64');
}

export type XenditQrCode = {
  id: string;
  external_id: string;
  qr_string: string;
  status: 'ACTIVE' | 'INACTIVE';
};

/**
 * Creates a dynamic QRIS code for a specific amount.
 *
 * `external_id` must be unique per request — it's how we correlate the
 * later webhook back to a `payment_intents` row, so it's generated by the
 * caller from that row's own id rather than left to chance here.
 */
export async function createQrCode(params: {
  externalId: string;
  amountIdr: number;
  callbackUrl: string;
}): Promise<XenditQrCode> {
  const res = await fetch(`${XENDIT_BASE}/qr_codes`, {
    method: 'POST',
    headers: {
      Authorization: authHeader(),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      external_id: params.externalId,
      type: 'DYNAMIC',
      callback_url: params.callbackUrl,
      amount: params.amountIdr,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Xendit createQrCode failed (${res.status}): ${body}`);
  }
  return res.json();
}

/**
 * Test-mode-only: fakes a successful scan-and-pay for a QR code already
 * created via `createQrCode`, triggering the same `qr.payment` webhook a
 * real payment would. Xendit rejects this outside sandbox keys — there is
 * no equivalent in live mode, by design.
 */
export async function simulateQrPayment(externalId: string, amountIdr: number): Promise<void> {
  const res = await fetch(
    `${XENDIT_BASE}/qr_codes/${encodeURIComponent(externalId)}/payments/simulate`,
    {
      method: 'POST',
      headers: {
        Authorization: authHeader(),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ amount: amountIdr }),
    },
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Xendit simulateQrPayment failed (${res.status}): ${body}`);
  }
}

export type XenditQrPaymentWebhook = {
  event: 'qr.payment';
  id: string;
  external_id?: string;
  amount: number;
  status: string;
  qr_code: { external_id?: string; id?: string };
};

/**
 * Verifies a webhook actually came from Xendit before trusting anything in
 * its body. Xendit's callback verification is a shared static token in the
 * `x-callback-token` header (configured in the Xendit dashboard, not
 * derived from the payload) — constant-time compared here so a timing
 * side-channel can't be used to guess it byte by byte.
 */
export function verifyWebhookToken(providedToken: string | null): boolean {
  const expected = process.env.XENDIT_CALLBACK_TOKEN;
  if (!expected || !providedToken) return false;

  const a = Buffer.from(expected);
  const b = Buffer.from(providedToken);
  return a.length === b.length && timingSafeEqual(a, b);
}
